name: 'GitHub Requested Reviewer Alerts'
description: 'Remind GitHub users of Pull Requests pending their reviews.'
inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'A GitHub Personal Access Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'