name: 'Pull Request Review Reminders'
description: 'Remind GitHub users of Pull Requests pending their reviews.'
inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'An Access Token for use with the GitHub API.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'