name: 'GitHub Requested Reviewer Alerts'
description: 'Notify GitHub users of Pull Requests pending their reviews.'
inputs:
  github-access-token:
    description: 'A GitHub Personal Access Token'
    required: true
  github-repository:
    description: 'The name of the GitHub Repository (e.g. "owner/repo-name")'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    - GITHUB_ACCESS_TOKEN=${{ inputs.github-access-token }}
    - GITHUB_REPOSITORY=${{ inputs.github-repository }}