name: 'GitHub Requested Reviewer Alerts'
description: 'Notify GitHub users of Pull Requests pending their reviews.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    - GITHUB_ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
    - GITHUB_OWNER_NAME=${{ GITHUB_OWNER_NAME }}
    - GITHUB_REPOSITORY_NAME=${{ GITHUB_REPOSITORY_NAME }}