name: 'Pull Request Review Reminders'
description: 'Remind GitHub users of Pull Requests pending their reviews.'
inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'An Access Token for use with the GitHub API.'
    required: true
  MINIMUM_ELAPSED_HOURS:
    description: 'The minimum number of hours elapsed since a review was requested at which reminders should be sent.'
    required: true
    default: 4
runs:
  using: 'docker'
  image: 'Dockerfile'