name: 'Pull Request Review Reminder Action'
description: 'Notify reviewers of Pull Requests awaiting their review.'
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node index.js