name: 'Pull Request Review Reminder Action'
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: totallyquiche/github-pull-request-review-reminder-action@latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: node index.js